version: '3.7'

services:
  postgres-hero:
    hostname: postgres-hero
    image: postgres:11
    container_name: hero-postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hero
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=masterkey
